branches:
  only:
    - master
    - develop
language: node_js
node_js: '10'
cache:
  directories: '${HOME}/.cache/yarn'
deploy:
  # deploy develop → front-dev.lunit.io
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: front-dev.lunit.io/shkyung
    skip_cleanup: true
    region: ap-northeast-2
    local_dir: build
    on:
      branch: master